FROM pigeosolutions/python-uwsgi

MAINTAINER Jean Pommier "jean.pommier@pi-geosolutions.fr"

USER root
COPY docker/resources /
COPY requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
RUN chmod +x /docker-entrypoint.sh /docker-entrypoint.d/*
COPY --chown=www:www app /app
WORKDIR "/app"

USER www
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["uwsgi", "--http", ":5000", "--chdir", "/app", "--wsgi-file", "main.py", "--callable", "app", "--master", "--processes", "4", "--threads", "2", "--uid", "www", "--stats", "127.0.0.1:9191"]
